-- MySQL Script generated by MySQL Workbench
-- seg 14 fev 2022 23:58:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema maosdadas
-- -----------------------------------------------------
USE `apidb` ;

-- -----------------------------------------------------
-- Table `apidb`.`tb_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_tokens`;

CREATE TABLE `tb_tokens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `value` TEXT NOT NULL,
  `user_agent` TEXT NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `tb_accounts`;

CREATE TABLE `tb_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `first_name` varchar(150) NOT NULL,
  `second_name` varchar(150) DEFAULT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(150) NOT NULL,
  `url_image` TEXT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE = InnoDB;
