-- MySQL Script generated by MySQL Workbench
-- seg 14 fev 2022 23:58:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema maosdadas
-- -----------------------------------------------------
USE `apidb` ;

-- -----------------------------------------------------
-- Table `maosdadas`.`tb_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_accounts`;

CREATE TABLE `tb_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL,
  `second_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `status` int(11) NOT NULL DEFAULT 1,
  `password` varchar(255) NOT NULL,
  `url_image` TEXT NULL,
  `is_teacher` int(11) DEFAULT 0,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `maosdadas`.`tb_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_subjects`;

CREATE TABLE `tb_subjects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_activities`;
CREATE TABLE `tb_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account` INT NOT NULL,
  `id_subject` INT NOT NULL,
  `done_at` DATETIME NOT NULL,
  `num_questions` INT NOT NULL,
  `num_hits` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_activities_1_idx` (`id_account` ASC),
  INDEX `fk_tb_activities_subjects_idx` (`id_subject` ASC),
  CONSTRAINT `fk_tb_activities_accounts`
    FOREIGN KEY (`id_account`)
    REFERENCES `tb_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_activities_subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `tb_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `maosdadas`.`tb_avatars`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `maosdadas`.`tb_avatars` (
--   `id` INT NOT NULL AUTO_INCREMENT,
--   `id_account` INT NULL DEFAULT NULL,
--   `file` VARCHAR(255) NULL DEFAULT NULL,
--   `src_file` VARCHAR(255) NULL DEFAULT NULL,
--   `created_at` DATETIME NULL DEFAULT NULL,
--   `updated_at` DATETIME NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   INDEX `fk_tb_avatars_accounts_idx` (`id_account` ASC),
--   CONSTRAINT `fk_tb_avatars_accounts`
--     FOREIGN KEY (`id_account`)
--     REFERENCES `maosdadas`.`tb_accounts` (`id`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_suggestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_suggestions`;
CREATE TABLE IF NOT EXISTS `tb_suggestions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `account_name` VARCHAR(150) NULL DEFAULT NULL,
  `account_email` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`1a`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `maosdadas`.`1a` (
--   `id1a` INT NOT NULL,
--   PRIMARY KEY (`id1a`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_job_positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_job_positions`;
CREATE TABLE IF NOT EXISTS `tb_job_positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_institutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_institutions`;
CREATE TABLE IF NOT EXISTS `tb_institutions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `state` VARCHAR(2) NULL,
  `url_image` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `maosdadas`.`tb_contests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_contests`;
CREATE TABLE IF NOT EXISTS `tb_contests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_institution` INT NOT NULL,
  `id_job_position` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `year` INT NOT NULL,
  `url_reference` VARCHAR(150) NULL,
  `status` VARCHAR(20) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_contests_1_idx` (`id_job_position` ASC),
  INDEX `fk_tb_contests_2_idx` (`id_institution` ASC),
  CONSTRAINT `fk_tb_contests_1`
    FOREIGN KEY (`id_job_position`)
    REFERENCES `maosdadas`.`tb_job_positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_contests_2`
    FOREIGN KEY (`id_institution`)
    REFERENCES `maosdadas`.`tb_institutions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `maosdadas`.`tb_disciplines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_disciplines`;
CREATE TABLE IF NOT EXISTS `tb_disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_study_plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_study_plans`;
CREATE TABLE IF NOT EXISTS `tb_study_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_contest` INT NOT NULL,
  `id_discipline` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `status` VARCHAR(20) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_studies_plan_1_idx` (`id_contest` ASC),
  INDEX `fk_tb_study_plans_1_idx` (`id_discipline` ASC),
  CONSTRAINT `fk_tb_studies_plan_1`
    FOREIGN KEY (`id_contest`)
    REFERENCES `maosdadas`.`tb_contests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_study_plans_1`
    FOREIGN KEY (`id_discipline`)
    REFERENCES `maosdadas`.`tb_disciplines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_discipline_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_discipline_subjects`;
CREATE TABLE IF NOT EXISTS `tb_discipline_subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_discipline` INT NOT NULL,
  `id_subject` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_themes_subjects_themes_idx` (`id_discipline` ASC),
  INDEX `fk_tb_themes_subjects_subjects_idx` (`id_subject` ASC),
  CONSTRAINT `fk_tb_themes_subjects_themes`
    FOREIGN KEY (`id_discipline`)
    REFERENCES `maosdadas`.`tb_disciplines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_themes_subjects_subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `maosdadas`.`tb_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_study_plan_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_study_plan_subjects`;
CREATE TABLE IF NOT EXISTS `tb_study_plan_subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_subject` INT NOT NULL,
  `id_study_plan` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_study_plan_subjects_1_idx` (`id_study_plan` ASC),
  INDEX `fk_tb_study_plan_subjects_2_idx` (`id_subject` ASC),
  CONSTRAINT `fk_tb_study_plan_subjects_1`
    FOREIGN KEY (`id_study_plan`)
    REFERENCES `maosdadas`.`tb_study_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_study_plan_subjects_2`
    FOREIGN KEY (`id_subject`)
    REFERENCES `maosdadas`.`tb_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_stages`;
CREATE TABLE IF NOT EXISTS `tb_stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `index_order` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_contents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_contents`;
CREATE TABLE IF NOT EXISTS `tb_contents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_stage` INT NOT NULL,
  `id_subject` INT NOT NULL,
  `id_study_plan_subject` INT NOT NULL,
  `name` VARCHAR(250) NULL,
  `url_item` VARCHAR(250) NULL,
  `description` VARCHAR(250) NULL,
  `index_order` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_contets_stage_2_idx` (`id_stage` ASC),
  INDEX `fk_tb_contents_stage_subject_1_idx` (`id_subject` ASC),
  INDEX `fk_tb_subject_contents_stage_1_idx` (`id_study_plan_subject` ASC),
  CONSTRAINT `fk_tb_contets_stage_2`
    FOREIGN KEY (`id_stage`)
    REFERENCES `maosdadas`.`tb_stages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_contents_stage_subject_1`
    FOREIGN KEY (`id_subject`)
    REFERENCES `maosdadas`.`tb_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_subject_contents_stage_1`
    FOREIGN KEY (`id_study_plan_subject`)
    REFERENCES `maosdadas`.`tb_study_plan_subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_enrolled_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_enrolled_accounts`;
CREATE TABLE IF NOT EXISTS `tb_enrolled_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account` INT NOT NULL,
  `id_contest` INT NOT NULL,
  `id_study_plan` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_account_study_plans_1_idx` (`id_account` ASC),
  INDEX `fk_tb_enrolled_accounts_2_idx` (`id_contest` ASC),
  INDEX `fk_tb_enrolled_accounts_3_idx` (`id_study_plan` ASC),
  CONSTRAINT `fk_tb_enrolled_accounts_1`
    FOREIGN KEY (`id_account`)
    REFERENCES `maosdadas`.`tb_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enrolled_accounts_2`
    FOREIGN KEY (`id_contest`)
    REFERENCES `maosdadas`.`tb_contests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enrolled_accounts_3`
    FOREIGN KEY (`id_study_plan`)
    REFERENCES `maosdadas`.`tb_study_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maosdadas`.`tb_progress_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_progress_accounts`;
CREATE TABLE IF NOT EXISTS `tb_progress_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account` INT NOT NULL,
  `id_content` INT NOT NULL,
  `status` VARCHAR(20) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_progress_accounts_1_idx` (`id_account` ASC),
  INDEX `fk_tb_progress_accounts_2_idx` (`id_content` ASC),
  CONSTRAINT `fk_tb_progress_accounts_1`
    FOREIGN KEY (`id_account`)
    REFERENCES `maosdadas`.`tb_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_progress_accounts_2`
    FOREIGN KEY (`id_content`)
    REFERENCES `maosdadas`.`tb_contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- ADDING CONSTRAINTS
ALTER TABLE tb_study_plans ADD CONSTRAINT constraint_tb_study_plans UNIQUE KEY(id_contest, id_discipline);
ALTER TABLE tb_study_plan_subjects ADD CONSTRAINT constraint_tb_study_plan_subjects UNIQUE KEY(id_subject, id_study_plan);
ALTER TABLE tb_discipline_subjects ADD CONSTRAINT constraint_tb_discipline_subjects UNIQUE KEY(id_discipline, id_subject);
ALTER TABLE tb_enrolled_accounts ADD CONSTRAINT constraint_tb_enrolled_accounts UNIQUE KEY(id_account, id_contest, id_study_plan);
ALTER TABLE tb_progress_accounts ADD CONSTRAINT constraint_tb_progress_accounts UNIQUE KEY(id_account, id_content);


-- Data
INSERT INTO tb_accounts ( id, first_name, second_name, email, status, password, is_teacher, created_at ) VALUES (1,'Cesar','Vianna','cesar.vianna@gmail.com',1,'$2y$10$aNvijBirIg3vSRf6skVVsefgQ426IkPElWGkIpdlwqnX5.5y4125G', 1, current_time);


-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (1, 'Banco de Dados', current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (2, 'CSS', current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (3, 'Desenvolvimento Web', current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (4, 'HTML',current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (5, 'Javascript',current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (6, 'Linux',current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (7, 'Lógica de Programação',current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (8, 'PHP',current_time );
-- INSERT INTO tb_subjects (id,  name ,created_at ) VALUES (9, 'Sistemas Operacionais',current_time );

-- INSERT INTO tb_disciplines(id, name, created_at) VALUES (1, 'Informática', current_time);
-- INSERT INTO tb_disciplines(id, name, created_at) VALUES (2, 'Português', current_time);

-- INSERT INTO tb_stages(id, name, index_order, created_at) VALUES (1, 'Aquisição', 1, current_time);
-- INSERT INTO tb_stages(id, name, index_order, created_at) VALUES (2, 'Esquematização', 2, current_time);
-- INSERT INTO tb_stages(id, name, index_order, created_at) VALUES (3, 'Revisão', 3, current_time);
-- INSERT INTO tb_stages(id, name, index_order, created_at) VALUES (4, 'Testes', 4, current_time);

-- INSERT INTO tb_institutions(id, name, created_at) VALUES (1, 'Policia Civil RS', current_time );
-- INSERT INTO tb_institutions(id, name, created_at) VALUES (2, 'SERPRO', current_time );

-- INSERT INTO tb_job_positions(id, name, created_at) VALUES (1, 'Agente Penitenciário', current_time );
-- INSERT INTO tb_job_positions(id, name, created_at) VALUES (2, 'Delegado', current_time );
-- INSERT INTO tb_job_positions(id, name, created_at) VALUES (3, 'Escrivão', current_time );
-- INSERT INTO tb_job_positions(id, name, created_at) VALUES (4, 'Investigador', current_time );
-- INSERT INTO tb_job_positions(id, name, created_at) VALUES (5, 'Perito Criminal', current_time );

-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,1, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,2, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,3, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,4, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,5, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,6, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,7, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,8, current_time);
-- INSERT INTO tb_discipline_subjects(id_discipline, id_subject, created_at) VALUES (1,9, current_time);


-- INSERT INTO tb_contests(id, name, id_institution, id_job_position, year, status, created_at) VALUES (1, 'Concurso SUSEPE', 1, 1, 2020, 'published' ,current_time);

-- INSERT INTO tb_study_plans (id, id_contest, id_discipline, name, status, created_at) VALUES (1, 1, 1, 'Plano de Estudos - SUSEPE RS - Informática', 'published', current_time);
-- INSERT INTO tb_study_plans (id, id_contest, id_discipline, name, status, created_at) VALUES (2, 1, 2, 'Plano de Estudos - SUSEPE RS - Português ', 'published', current_time);

-- INSERT INTO tb_enrolled_accounts (id, id_account, id_contest, id_study_plan, created_at, updated_at) VALUES (1, 1, 1, 1, current_time, current_time);
-- INSERT INTO tb_enrolled_accounts (id, id_account, id_contest, id_study_plan, created_at, updated_at) VALUES (2, 1, 1, 2, current_time, current_time);

-- DATA
-- INSERT INTO `tb_accounts` ( id, first_name, second_name, email, status, password, created_at, is_teacher ) VALUES
--   (1,'Cesar','Vianna','cesar.vianna@gmail.com',1,'$2y$10$aNvijBirIg3vSRf6skVVsefgQ426IkPElWGkIpdlwqnX5.5y4125G',current_time,1),
--   (2,'Paula','Pereira de Castro','paulap.castro@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (3,'MÃ¡rcia','da Silva e Silva','marciaesilva2020@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (4,'Rubiana','Padilha da Silva Pasa','rubianapasa@outlook.com',1,'$2y$10$nup/OSBxZhv1fflFUqV9V.JXpNn.5xHTps4fb1s3LOaEHOiwJMCde',current_time,0),
--   (5,'Deise','Neis Bueno','deiseneisbueno@yahoo.com.br',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (6,'Ana Clara','dos Santos Cesa e Silva','anacesa@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (7,'Tatiana','Amaro','tatiaamaro@hotmail.com',1,'$2y$10$J.mrv/1l5BX3CpWD63F2MeUcRPdqLMLI34B8H9R0/i0/38G0qfAIS',current_time,0),
--   (8,'Luiz Antonio','Garcia de Abreu','luizantoniogarciadeabreu@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (9,'Jacqueline','Rodrigues de Albuquerque','jack_albuquerque@hotmail.com',1,'$2y$10$z6Ouh1VAz8S3sQ9atlbi/OTrrOuiX7rFtQY39rbDwJFhCE.PUDksi',current_time,0),
--   (10,'Giovani','Soares Bonatto','bonatto.giovani@gmail.com',1,'$2y$10$bIZ7Fp7tn8BNRV4JNoi3bOFK3miibGt4jxLZXHwv5N9GPb/6xvDby',current_time,0),
--   (11,'Douglas Henrique','da Rosa Gomes','douglashrg.dan@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (12,'Giovanna ','MattÃ© de Souza','gmsouza.adv@outlook.com',1,'$2y$10$T/rfOE08xI51ID3MTkDaPOQdQcTeFmIunkVrvgVoAgxLYFFpqWrRi',current_time,0),
--   (13,'Luana','Piovesan','lu.piovesan@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (14,'Georgeton','Santos Ferreira','g9.george@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (15,'Rejane','Aparecida Silva dos Santos Cabral','rejanessilva77@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (16,'Tabata','Lima Palskuski','tabatapalskuski@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (17,'Juliane','Rios Petrarca','petrarcaju@gmail.com',1,'$2y$10$/ZaUa6rh2SxpktxOKCTJ7uZE8Kq5/I3eyKkHULieOpCFQQ9lD83gC',current_time,0),
--   (18,'Carolina','RÃ¼besam Ourique','carolinaourique79@gmail.com',1,'$2y$10$DQm/QkfaOJmmYhsvMATr4.WVlBf9OWbWt3Bdnidsx6cRVNWV5OKvy',current_time,0),
--   (19,'Mariana','Lessa','lessa6@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (20,'Mariana','Clezar Lafin','marianalafin@hotmail.com',1,'$2y$10$17.yLi5gIPSJLflq.gs9beXjRNkMicE6XIPV/iZiJozuMVRNNT10W',current_time,0),
--   (21,'Andressa','da Silva Andrade','andrade__andressa@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (22,'Ricardo','Daniel Silva de Souza','ricardodss7@gmail.com',1,'$2y$10$ODG5syJZTbKWJllc41yuUeS53txeg75TaKXJDlTiXe61TcD7wGe2a',current_time,0),
--   (23,'Paula','Giampaoli da Silva','paulinhags@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (24,'Cris','','csconsorti@gmail.com',1,'$2y$10$8BTd1ymc838JER5.Yb15H.KkCeWOM9vOKo9jUFtJ6Q8HQCH76ln.y',current_time,0),
--   (25,'Jaqueline','Diel Alberton','jaquelinedalberton@gmail.com',1,'$2y$10$fqMZ5bKg1SuBppFgFzNLR.SFd0Ir9bOa/g8oyuTq9PRoO8Xdqya6O',current_time,0),
--   (26,'ThomÃ¡s','Bortolini','th_bortolini@hotmail.com',1,'$2y$10$54QTt8kitQQ1FvOzCG3CquoiAG0URYGp2tbRmAYu71b2rfLpZcSBe',current_time,0),
--   (27,'Marlene','Magagna Wisnieski','wisnieski@hotmail.com',1,'$2y$10$aNvijBirIg3vSRf6skVVsefgQ426IkPElWGkIpdlwqnX5.5y4125G',current_time,0),
--   (28,'Paola','Fornari Vanni','paolavanni@gmail.com',1,'$2y$10$3X7kezcDxlXm9p0tBoQdsO1odU.CvCgHC1vtTBUXOd9ChGhFyT9e2',current_time,0),
--   (29,'Bruna','Pazini Hoch','brunapazini@outlook.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (30,'Janaina','Mendes Von Muhlen','jana.mv@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (31,'Karen','Fialho','karenfialho.81@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (32,'Jaime','Oronil carvalho trindade','jaimecarvalho1903@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (33,'FÃ¡bio','de AraÃºjo Ricardo','fabio.corsan6@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (34,'Gilnei','Lino Bertuol','bertuolgilnei@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (35,'Aline','Mendes Rosa Stein','alinesthein@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (36,'Tamara','Gutierres','tamaragutierres14@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (37,'Emanuela','Fiorelli','manufiorelli4@gmail.com',1,'$2y$10$xcXv5Gbj1Q4JiDBQk1gTOOjdvJf83bXLrPju/4rxF3078C9W1Kv46',current_time,0),
--   (38,'Rosane','A. Radin Dornelles','rosaneradin@yahoo.com.br',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (39,'LetÃ­cia','da Silva Senna','lesenna3@hotmail.com',1,'$2y$10$MhwXsf5Uh2Uw/zX2vMTxEe49dL/qDmD9.XqKPmVXMLd76zjiYTBme',current_time,0),
--   (40,'Raquel','Vasconcelos Medeiros','falecomaraquel@gmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (41,'LÃ­gia','ValÃ©ria Bernardi','lvbernardi@hotmail.com',1,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (42,'Daiana','MÃ¼nchen','daiana-km@hotmail.com',1,'$2y$10$FTKqomkw/OIeqqa9q2qSGeeoN/C2qFtEfirovh6UB2UsueF42.HP2',current_time,0),
--   (43,'Luciele','Trentini','lucieletrentini@hotmail.com',0,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (44,'Caroline','Nauter','carolinenauter@gmail.com',0,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (45,'Taiane','Escobar','taianeescobar@hotmail.com',0,'$2y$10$9Jemnzqn23Vm8j8CcBPdkefjdbNSqWpE/bm9Yh37AVQa4Dy/NJsRG',current_time,0),
--   (47,'Lisieli','Venturini Baratto','lisielivb@hotmail.com',1,'$2y$10$UZl7TvR70wMVx52HV6sKgO5EudPdxAgTidmtEzMKYeXsihxubqCVq',current_time,0),
--   (48,'Danielle','Dutra Rodrigues','danidutrar@hotmail.com',1,'$2y$10$R3d24r2pq4xO0pihieir9.5SmZ7aRMtbcCU4GdWr0crNwKKeKJ9Fy',current_time,0),
--   (49,'MARIANA','LONGARETTI','144065@upf.br',1,'$2y$10$BW3Ax8kp237dlPUTVRt7ueALaG0vhSQzOCHq6JHiuCR1d64faGyXa',current_time,0),
--   (50,'Mateus','LuÃ­s lenhard','mateusllenhard@yahoo.com.br',1,'$2y$10$ANzV8NBIwDM5cm0fETC7Q.Iter02ybRpar7rnahfN0Wh3mWO3qATS',current_time,0),
--   (52,'Ana Paula','Batista','paulasilvabatista@gmail.com',1,'$2y$10$kh7.zPJVPTY1UG2YeEIZjuWdUfnjTSoLczHrwRCvUeQzjTX4chRlS',current_time,0),
--   (53,'ISABEL','PAIM DOS SANTOS','belapaim@gmail.com',1,'$2y$10$ycPWPqjCBgVYF.6bhHzzsOSAEQTkpSnCFfFEvDDStJMLDIZQv5Q72',current_time,0),
--   (54,'Angelo','Suita Freitas','angelosuita@gmail.com',1,'$2y$10$ugqiqdfpf5mdFf8zfBV09O.0rpAvAxtKnSfb0v0aX/oEbVyMr/X4e',current_time,0),
--   (55,'Leticia','Bonetti','leticiabonetti@hotmail.com',1,'$2y$10$GusAGj2QXzO7AW2DmzS1ieWNUXBkONeUWLo7X/F9MsHMI8cYpOGxi',current_time,0),
--   (56,'Ammanda','Borghetti','ammandaborghetti@gmail.com',1,'$2y$10$OKafKHknt7iGuS8MLYzqPuz0dNJ5vlFITRdYWq4cz.3kUT0QbFzE2',current_time,0),
--   (57,'Camila','Zaltron','z-camilinha@hotmail.com',1,'$2y$10$cmIa9x/erre12edu0vL.ZeaBJMhVBx47T9ng6ZSGOWhd7IbXU5ywu',current_time,0),
--   (58,'Lais VerÃ´nica','Pereira de Santana','laisveronicca@live.com',1,'$2y$10$c.LOU9WNYDZ3a4pSiPpWJenGO7Pfkdbutdy00//yttjnUx1L9Rkb2',current_time,0),
--   (59,'JÃºlia Denardin','Denardin','juliadenardin@gmail.com',1,'$2y$10$g8TqRMs0eO6Dy00vhbR/7u5SURK9a91jSCBF33VGkGhUVgmAdqINC',current_time,0),
--   (60,'Sandra AndrÃ©a','Haag Padilha','adv.sandra.andrea@gmail.com',1,'$2y$10$xmPDCFemi6qxPVJ.HaNpjOi/PEjTgMQOeYpWkLONrkqRr2t9BYnkS',current_time,0),
--   (61,'Noely','Lopes de Moraes','moraesnoely@gmail.com',1,'$2y$10$vPVClHe7nWloFIoGL56GuOKSO0YLfTAQ5pI6t9M8D9sONY/LBlq6i',current_time,0),
--   (62,'Roberto','Jacobi de Oliveira','robertojacobi85@gmail.com',1,'$2y$10$EfQQ2uwZUJEOPBltc6uHHeb7KAFTaHHEtKxOoe1Jnx5P4OVW0IqMG',current_time,0),
--   (63,'Carine','Tomaz','carine-tomaz@hotmail.com',1,'$2y$10$xkursrNwkuoV7HukACPiUOgf0VmZEgAF6QloaqE4t9irk9AFhN8CG',current_time,0),
--   (64,'Jonas','Matias Assmann','jonas_assmann@hotmail.com',1,'$2y$10$XjC3/SlXacGfX1tfwpjUpectwFJ2CcWqdxWjbgA2.pfaEwn9HakJu',current_time,0),
--   (65,'Ricardo','Silveira','rsilveira1987@gmail.com',1,'$2y$10$uuTHhkRsyvLD4OqSvmucz.C/PbKyQyUGURVXOJoc4oo2fEcpyNLOO',current_time,0);
